### ISSUE TITLE
Cannot reproduce evaluation results correctly.

### ISSUE THREAD

**Issue by natsala13** [tr3e/InterGen#10]
Thank you very much for your work and the new dataset!
I am trying to reproduce your results with your given model `checkpoints/intergen.ckpt` and for some reason don't get the same results.

========== MM Distance Summary ==========
---> [ground truth] Mean: 3.7849 CInterval: 0.0012
---> [InterGen] Mean: 3.7978 CInterval: 0.0011
========== R_precision Summary ==========
---> [ground truth](top 1) Mean: 0.2491 CInt: 0.0048;(top 2) Mean: 0.3828 CInt: 0.0064;(top 3) Mean: 0.4780 CInt: 0.0076;
---> [InterGen](top 1) Mean: 0.2748 CInt: 0.0042;(top 2) Mean: 0.4065 CInt: 0.0052;(top 3) Mean: 0.4881 CInt: 0.0050;
**========== FID Summary ==========
---> [ground truth] Mean: 0.9993 CInterval: 0.0211
---> [InterGen] Mean: 7.1862 CInterval: 0.1244**

These are the results I get. Looking at the FID summary, The groundtruth's mean is 0.9993 and Intergen's mean is 7.1862 while in your paper your results are 0.273 for the ground truth and 5.918 for Intergen's model.

Thank you!

**Comment by tr3e** [comment]
Sorry for that, there are some typos in evaluator.py. We have already fixed that.
please make sure your code is up to date.

**Comment by Xiyan-Xu** [comment]
Based on your result, I noticed that the R-precision here is also quite different. Have you changed the batch_size? That can make quantitative result quite different.
