### ISSUE TITLE
Question About the shape of npy file in motion_processed?

### ISSUE THREAD

**Issue by VankouF** [tr3e/InterGen#15]
After I load one npy file in motino_process, I notice the shape of it is T*492. 
**I am curious about the concret meaning of 492**, what are the components in 492?  In the code, I understand it contains the global postion for 22x3 and 6D rotation represention for 21x3, How about the others?

**Comment by tr3e** [comment]
The others are for hand joints. Although hand motion is not provided in this version, we retain the SMPL-H style representation for future works involving more fine-grained interaction of hands.

**Comment by VankouF** [comment]
Thanks!
