### ISSUE TITLE
latest evaluator.py

### ISSUE THREAD

**Issue by boyuaner** [tr3e/InterGen#26]
Sorry for that, there are some typos in evaluator.py. We have already fixed that.
please make sure your code is up to date.

_Originally posted by @tr3e in https://github.com/tr3e/InterGen/issues/10#issuecomment-1790679873_
--------            
Sorry, but I cannot find the latest evaluator.py after Nov 2, 2023..?

**Comment by accountWang** [comment]
您好，我也没有找到最新的 evaluator.py。请问您找到了吗

**Comment by RunqiWang77** [comment]
I also can't find the latest evaluator.py after November 2, 2023. Have you found it now?
