### ISSUE TITLE
WRONG 6d rotation params of motion_processed about joint 20(left_hand) and 21(right_hand)

### ISSUE THREAD

**Issue by boyuaner** [tr3e/InterGen#29]
Hello,

I'm attempting to perform the FK from the processed motion data, which contains pos(22*3), vel(22*3), and rot(21*6). I have extracted rotation data from that, yet I found that the last 2 joints' rotation(which refer to hands)  are something like [1, 0, 0, 1, 0, 0], which would be the wrong 6d representation.

**Comment by tr3e** [comment]
Sorry for the confusion. It is indeed a 6D rotation as the first two columns of a 3x3 matrix. But I rearrange its order as rot_mat[:, :2]. So it's actually [a,c,e,b,d,f] for some [a,b,c,d,e,f] our cases, and it's [1, 0, 0, 0, 1, 0] for [1, 0, 0, 1, 0, 0].

**Comment by boyuaner** [comment]
Thank you for your replication, but I still feel confused. If as you said, rot_mat[:, :2] here still means taking the first two columns of the matrix, why rearrange the order? So do all 6d representation in motion_processed need to permute(0, 2, 4, 1, 3, 5)?

**Comment by tr3e** [comment]
> Thank you for your replication, but I still feel confused. If as you said, rot_mat[:, :2] here still means taking the first two columns of the matrix, why rearrange the order? So do all 6d representation in motion_processed need to permute(0, 2, 4, 1, 3, 5)?

Yeah, the permutation is necessary if compatibility with the existing implementation is what you want.

**Comment by boyuaner** [comment]
Okay, but I still want to know the purpose of rearrangement :)

**Comment by boyuaner** [comment]
https://github.com/tr3e/InterGen/assets/32932640/eaba6e02-ad6b-4694-8b36-ad4954d47b0c

this is the FK result(green), and joint position(red) visualization result of case3292.
It looks like an offset issue, I used the following offset(T pose) settings:
```
Tpose_offset = np.array([
    [ 0,  0,  0],
    [ 1,  0,  0],
    [-1,  0,  0],
    [ 0,  1,  0],
    [ 0, -1,  0],
    [ 0, -1,  0],
    [ 0,  1,  0],
    [ 0, -1,  0],
    [ 0, -1,  0],
    [ 0,  1,  0],
    [ 0,  0,  1],
    [ 0,  0,  1],
    [ 0,  1,  0],
    [ 1,  0,  0],
    [ -1,  0,  0],
    [ 0,  0,  1],
    [ 1,  0,  0],
    [-1,  0,  0],
    [ 1,  0,  0],
    [-1,  0,  0],
    [ 1,  0,  0],
    [-1,  0,  0]])
```

**Comment by tr3e** [comment]
Oh, it is because our Tpose_offset is based on SMPL template, that is not straightly aligned to the frame axis.
We hope the nets to learn to encode the SMPL shape using shape-dependent joint positions and rotations.
I recommend applying Smplify or some other SMPL-based IK to retrieve the corresponding shape and Tpose offset if you want.

**Comment by boyuaner** [comment]
Thank you for your patient explanation! I successfully decoded the .pkl file using the SMPL tool and obtained a consistent 6d representation with .npy in motion_processed :)
