### ISSUE TITLE
Error occurs when running infer.py

### ISSUE THREAD

**Issue by Xiyan-Xu** [tr3e/InterGen#5]
Thanks a lot for your great work. I'd like to know why I encountered an error when I try to run infer.py. Here is the error info I encountered:

> Traceback (most recent call last):
>   File "tools/infer.py", line 126, in <module>
>     litmodel.generate_one_sample(text, name+"_"+str(i))
>   File "tools/infer.py", line 65, in generate_one_sample
>     self.plot_t2m([motion_output[0], motion_output[1]],
>   File "tools/infer.py", line 49, in plot_t2m
>     plot_3d_motion(result_path, paramUtil.t2m_kinematic_chain, mp_joint, title=caption, fps=30)
>   File "/home/ubuntu/xiyan/InterGen/tools/../utils/plot_script.py", line 129, in plot_3d_motion
>     ani.save(save_path, fps=fps)
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/animation.py", line 1090, in save
>     anim._init_draw()  # Clear the initial frame
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/animation.py", line 1748, in _init_draw
>     self._draw_frame(frame_data)
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/matplotlib/animation.py", line 1767, in _draw_frame
>     self._drawn_artists = self._func(framedata, *self._args)
>   File "/home/ubuntu/xiyan/InterGen/tools/../utils/plot_script.py", line 104, in update
>     ax.lines = []
> AttributeError: can't set attribute

**Comment by tr3e** [comment]
Please make sure your matplotlib version is exactly 3.2.0, on which I tested.

**Comment by Xiyan-Xu** [comment]
That works, thank you!
