### ISSUE TITLE
NPY Processed Motion Representation 

### ISSUE THREAD

**Issue by jwgreens** [tr3e/InterGen#6]
Hello! First, let me thank you for your paper and released code/dataset!

I was wondering if you could share the precise format of the '.npy' files in _motions_processed_.

I understand from preprocess.py you append the joint positions and rotations. 

I'm curious where joint velocities and foot-ground features are located within the file format, as well as other pertinent info. 

Thanks!

**Comment by tr3e** [comment]
It is in process_motion_np( ).

**Comment by jwgreens** [comment]
Thank you for pointing me in the right direction! That's exactly what I needed.
